export const GET_ALL_TABLETS = 'GET_ALL_TABLETS'
export const GET_ALL_TABLETS_SUCCESS = 'GET_ALL_TABLETS_SUCCESS'
export const GET_ALL_TABLETS_FAILED = 'GET_ALL_TABLETS_FAILED'

export const ON_SELECT_TABLET = 'ON_SELECT_TABLET'
export const ON_SELECT_TABLET_SUCCESS = 'ON_SELECT_TABLET_SUCCESS'
export const ON_SELECT_TABLET_FAILED = 'ON_SELECT_TABLET_FAILED'